# https://raw.githubusercontent.com/hbstack/site/main/config/_default/menus.en.yml

main:
  - name: Books
    identifier: book
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
  - name: Tags
    identifier: patterns
    weight: 1000
    params:
      icon:
        name: boxes
        #color: 'skyblue'
        className: text-primary