title_separator: '|'
title_sections: false # when false, remove the sections from the title.
# title_sections_depth: 1 # the depth of sections on the title.
# title_sections_depth_dir: start # when start, the depth is counting from the root sections.

description: >
 Empower your Java skills with ClojureForJava.com. 
 Explore our comprehensive 32-book series designed to seamlessly transition Java developers to Clojure, 
 specifically tailored for enterprise and financial environments.
code_block_panel:
  max_lines: 100


meta: 
  date: false
  reading_time: false
  
hb:
  # override SASS variables, please replace the dash with underline, e.g. `list-group-color` should be `list_group_color`.
  styles:
    # https://imagecolorpicker.com/color-code/094e15
    primary: '#0004FF'
  

  full_width: true
  revision:
    created_at: false
    date_format: ':date_full'
    font_size: '.825rem'
    icons: true
  header:
    brand: Clojure for Java Developers
    socials:
      # github: hbstack
      # twitter: razonyang
      # rss: true
      # mastodon: https://techhub.social/@hbstack
  footer:
    powered_by: true
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
  terms:
    paginate: 100
  blog:
    sidebar:
      profile:
        title: Clojure for Java Developers
      posts:
        recent_count: 0
        featured_count: 0
        recent_posts: 0
        list_style: vertical
      taxonomies:
        count: true
        limit: 1000
        separate: false
        style: pills
        authors:
         title: Authors
         disable: false
         limit: 100
         weight: 4
        categories:
          disable: false
          weight: 1
          title: Categories
          limit: 1000
        series:
          disable: false
          limit: 100
          title: Series
          weight: 2
        tags:
          disable: false
          limit: 1000
          title: Tags
          weight: 3
    paginate: 4
    post_thumbnail_height: 4
    post_thumbnail: false
    related_posts:
      list_style: vertical
    home:
      taxonomies: false
      featured_posts: 0
      main_sections:
        - books
    #giscus:
      #repo: hbstack/theme
      #repo_id: R_kgDOJP3qtA
      #category_id: DIC_kwDOJP3qtM4CVavM
  docs:
    #https://hugomods.com/docs/comment-engines/giscus/
    giscus:
      repo: MasteryEducation/ClojureForJava.com
      repo_id: R_kgDOM7uc9w
      category: Announcements
      category_id: DIC_kwDOM7uc984CkY8R
      mapping: title
      strict_matching: true
      input_position: top
      reactions: true
      lazy_loading: true



  # https://hbstack.dev/modules/components/content-panel/
  content_panel:
    comments: false

seo:
  # https://hugomods.com/en/docs/seo/#favicons-module
  favicons: 
    icon: images/logo.png # use logo as favicon.

# https://hugomods.com/en/docs/pwa/#site-parameters
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'Clojure for Java Developers'

# https://hugomods.com/search/configurations/
search:
  stall_threshold: 300
  min_match_char_length: 2
  case_sensitive: false
  # shortcut_search: ["/"]

mermaid:
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
